env:
  global:
  - HUGO_VER: 0.38.2
language: generic
cache: false
branches:
  only:
  - master
notifications:
  email: true
  pushover:
    api_key:
      secure: snl4/MszuhdlqKyVDgmeiRoXQ0ilszm07TRQken5f0CsBK1MvRV/zimMM7L/mtEwsynP5+NslCjBBzWZaZLfWuagcV1brp068nwH7ayZ99sChPSGXdOoykW4dKGvXU0gxV2WySDyxeGjQnVUBMPmTe5j6peR716a4lT2tdCReET9yioXB4Ur19vZ/3FPb0pVDvhYEjAQWg6CII9QX+eXI9Q5EwvjKb7PHk0oKKTu/uiJ2xYxtL899t9Q08dHaMEefyBN0Xqx+sI7H9ojyYs7rnKj8MU7VkhCy/KYX0C+Cv3P/eOPjqd0Ec/641KTww/j0DZlU2SswQSYAiCrnGO0xNYaAWI/n6bj/7hpX7b3ONnVwgr2/SEge6CJCJjL0T8yGQZXsnCnt8ZLPh2mFcjvCF5Cg+SI96seFGmxWPFxAVAQtSjbu81cl0/ZKzdo3fJ98k+EqcLaBXoYwmhoFL9zfgebT/12rIhu/2PnvTLK6j4mzblk9Y8JBM8oyGxPLECACHEhcGxflZWKf26F5KuNCy5ywzYROwxqCGljWmI9OtEDvumUlHnFO9ZClyp+NNbhF8kXIjMdl40rX5ytEJk25bkcbbjkxfeKt6T4rSRNZIO4zD7Xw3e0NanpwiWwwRep8Ihz7oiJa2+GZ0D7F/B9MzwdUVNqt1xMkzfB8nf9VMU=
addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
before_script:
- curl --silent -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VER}/hugo_${HUGO_VER}_Linux-64bit.tar.gz
  | tar zxf -
script:
- "./hugo"
deploy:
  provider: gcs
  access_key_id: GOOGU2LT7AP6FT66C6RA
  secret_access_key:
    secure: ixYSUE429fQ6zgfN8ElFHFMIhaCA5prHkvmaHUi/QIPBVvUEvUpSPmak9kLJwEnZLCioMzI1bVtJcygLI67gX2dtkbUjb1MOaLR2QA0EDVXQtw00LMbK9fOlrPchB2qPzQoowYZt1P8sq5EeWeC04CjjPgY6W2rNfMpf8+mA0+ypCiIDyYSqbygSxQF71zbQVszCXayXl0dXvfqw7JNgWl56Q0JHxKSMpPivLyjSPRu97g8OBAoRjU18+lOcYXBzYv3v6MMGmHnyi7P+VhVlG+kWs0jEuyOt9FTh4fxqWIsmJ0unw97ZsbBvFIwBemJTZ5Dll00dGjc6AxIZpNtFw1vWuMZbAZdYlHW6AX5zQFg6klpGsVBo6ClxeY/hW6/WXYfsibvBhoApR4pOWot9qyD/rGXLls8YprX77YjIi4KXK9ucl5fsARxHRdm0aXH2Pev2AeqmxCJd8NIwUKMSg+1sDyQ3n2uQDYHW7jdDfIj7HbXkSvqkBRiZW3nDuj6zBhomDO7+EF556xdgr5cl7yHykCS2AnrzLk5UO6yoA/iKoSeRMklYCVlbgBUw/c+VCeXR3f0EN3MhUir8ZANW+Rq7yoFc6K7A9lTat0/BU4SGTzYjyMFYs6Ea6iYSCpGktQd/or/gChZ9gUtPxw3rNiE56lXiOcxR9Lvm0WzPY0Y=
  bucket: devopsish.com
  local-dir: public
  skip_cleanup: true
  acl: public-read
  detect_encoding: true
