branches:
  only:
  - master
notifications:
  email: true
cache: false
addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
before_script:
- curl --silent -L https://github.com/gohugoio/hugo/releases/download/v0.35/hugo_0.35_Linux-64bit.tar.gz
  | tar zxf -
script:
- GIT_COMMIT_SHA=`git rev-parse --verify HEAD` GIT_COMMIT_SHA_SHORT=`git rev-parse
  --short HEAD` ./hugo
deploy:
  provider: gcs
  access_key_id: GOOGU2LT7AP6FT66C6RA
  secret_access_key:
    secure: ixYSUE429fQ6zgfN8ElFHFMIhaCA5prHkvmaHUi/QIPBVvUEvUpSPmak9kLJwEnZLCioMzI1bVtJcygLI67gX2dtkbUjb1MOaLR2QA0EDVXQtw00LMbK9fOlrPchB2qPzQoowYZt1P8sq5EeWeC04CjjPgY6W2rNfMpf8+mA0+ypCiIDyYSqbygSxQF71zbQVszCXayXl0dXvfqw7JNgWl56Q0JHxKSMpPivLyjSPRu97g8OBAoRjU18+lOcYXBzYv3v6MMGmHnyi7P+VhVlG+kWs0jEuyOt9FTh4fxqWIsmJ0unw97ZsbBvFIwBemJTZ5Dll00dGjc6AxIZpNtFw1vWuMZbAZdYlHW6AX5zQFg6klpGsVBo6ClxeY/hW6/WXYfsibvBhoApR4pOWot9qyD/rGXLls8YprX77YjIi4KXK9ucl5fsARxHRdm0aXH2Pev2AeqmxCJd8NIwUKMSg+1sDyQ3n2uQDYHW7jdDfIj7HbXkSvqkBRiZW3nDuj6zBhomDO7+EF556xdgr5cl7yHykCS2AnrzLk5UO6yoA/iKoSeRMklYCVlbgBUw/c+VCeXR3f0EN3MhUir8ZANW+Rq7yoFc6K7A9lTat0/BU4SGTzYjyMFYs6Ea6iYSCpGktQd/or/gChZ9gUtPxw3rNiE56lXiOcxR9Lvm0WzPY0Y=
  bucket: devopsmeh.com
  local-dir: public
  on:
    repo: chris-short/devopsish.com
