baseURL = "/"
copyright = "[Some rights reserved](https://creativecommons.org/licenses/by-sa/4.0/)"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-4498776-13"
languageCode = "en-us"
metaDataFormat = "toml"
newContentEditor = "code"
paginate = 5
relativeURLs = true
theme = "hugo-theme-bootstrap4-blog"
title = "DevOps'ish"

[permalinks]
  post = ":slug/"
  page = ":slug/"

[params]
  author = "Chris Short"
  description = "DevOps, Cloud Native, Open Source, and the 'ish in between."
  favicon = "/favicons/favicon.ico"

  [params.sidebar]
    About = "DevOps'ish is a weekly newsletter assembled by open source contributor, DevOps veteran, and CNCF Ambassador [Chris Short](https://chrisshort.net/)."
    num_recent_posts = 4

[Author]
  name = "Chris Short"