[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.40.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.40.1"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy]
  command = "hugo --buildDrafts --buildFuture"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.40.1"
  HUGO_ENABLEGITINFO = "true"
