[build]
  publish = "public"
  command = "hugo"

[context.production]
  HUGO_VERSION = "0.39"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
[context.deploy-preview]
  HUGO_VERSION = "0.39"
  HUGO_ENABLEGITINFO = "true"
  command = "hugo --buildDrafts --buildFuture"
[context.branch-deploy]
  HUGO_VERSION = "0.39"
  HUGO_ENABLEGITINFO = "true"
  command = "hugo --buildDrafts --buildFuture"