[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.56.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.56.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.56.3"

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.56.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "**/*"

  [headers.values]
    cache-control = '''
    404.html,
    max-age=300'''

    cache-control = '''
    **/*.@(jpg|jpeg|gif|png|svg|css|js|eot|otf|ttf|ttc|woff*|pdf),
    /favicons/*,
    max-age=2764800'''

    Access-Control-Allow-Origin = "**/*.@(eot|otf|ttf|ttc|woff*|font.css)"

    X-Frame-Options = "SAMEORIGIN"

    Content-Security-Policy = "frame-ancestors 'self'"

    X-XSS-Protection = "1; mode=block"

    X-Content-Type-Options = "nosniff"

    Referrer-Policy = "no-referrer-when-downgrade"

    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

