[build]
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.39"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  command = "hugo -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.39"
  HUGO_ENABLEGITINFO = "true"
  command = "hugo -DF -b $DEPLOY_PRIME_URL"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.39"
  HUGO_ENABLEGITINFO = "true"
  command = "hugo -DF -b $DEPLOY_PRIME_URL"