[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.38.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.38.2"
  HUGO_ENABLEGITINFO = "true"
  command = "hugo -DF -b $DEPLOY_PRIME_URL"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.38.2"
  HUGO_ENABLEGITINFO = "true"
  command = "hugo -DF -b $DEPLOY_PRIME_URL"